### ISSUE TITLE
Automatically redirect https://leetcode.cn/ domain to https://leetcode.com/

### ISSUE THREAD

**Issue by architec** [architec/mistake#100]
Should automatically redirect the https://leetcode.cn domain to https://leetcode.com, while preserving the same page open.

For example, https://leetcode.cn/problems/remove-nth-node-from-end-of-list/ will be automatically redirected to https://leetcode.com/problems/remove-nth-node-from-end-of-list/

**Comment by Pushkarm029** [comment]
@architec can you assign me this issue?

**Comment by Pushkarm029** [comment]
@architec , You want to redirect the user to leetcode.com in a new tab when the user opens leetcode.cn.
or you want to save leetcode.com in the list instead of.cn. If not any of these, please explain the intentional behavior.

**Comment by architec** [comment]
in the same tab for redirect
