### ISSUE TITLE
open all links in a new tab, not current tab

### ISSUE THREAD

**Issue by architec** [architec/mistake#60]

**Comment by kokoaono** [comment]
Hello @architec. 
Can I work on this issue, please?

**Comment by Marob-nod** [comment]
Hello @architec , are your currently working on this issue ?

**Comment by kokoaono** [comment]
hello @architec 
can reassign to @Marob-nod :)
Thank you

**Comment by architec** [comment]
not stale

**Comment by architec** [comment]
not stale
