### ISSUE TITLE
Change the first url in footer

### ISSUE THREAD

**Issue by architec** [architec/mistake#73]
change https://github.com/architec/mistake/blob/e9f4ae426e60572c444d2a874d9f720037bcd1c4/src/pages/Popup/Popup.jsx#L228

to https://leetcode.com/tag/dynamic-programming/discuss/1050391/Must-do-Dynamic-programming-Problems-Category-wise

**Comment by architec** [comment]
@hua0-richard

**Comment by architec** [comment]
in progress

**Comment by kmc026** [comment]
I would like to help on this issue.

**Comment by architec** [comment]
will fix this issue
